server {
    listen 80;
    server_name localhost;

    # 1. Sirve los archivos del Frontend (React/Vite)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }

    # 2. Rutea al Backend de DESPACHOS por la red privada
    location /backend-despachos/ {
        # IMPORTANTE: Reemplaza con la IP PRIVADA de la EC2 donde están los backends
        proxy_pass http://10.0.2.52:8082/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Rutea al Backend de VENTAS por la red privada
    location /backend-ventas/ {
        # IMPORTANTE: Reemplaza con la misma IP PRIVADA de la EC2
        proxy_pass http://10.0.2.52:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}