name: CI/CD Backend Despachos

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-push-deploy-despachos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Si usas cuenta de AWS Academy/Learner Lab, descomenta la siguiente línea:
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push Despachos a ECR
        run: |
          cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker build -t app-backend-despachos .
          docker tag app-backend-despachos:latest ${{ secrets.ECR_REPO_URL_DESPACHOS }}:latest
          docker push ${{ secrets.ECR_REPO_URL_DESPACHOS }}:latest

      - name: Desplegar Despachos vía SSM (Docker Compose)
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "set -e",
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "mkdir -p /home/ec2-user/app",
              "cd /home/ec2-user/app",
              "sudo docker-compose pull app-backend-despachos",
              "sudo docker-compose up -d --no-deps app-backend-despachos"
            ]}' \
            --query "Command.CommandId" \
            --output text)
            
          echo "Comando enviado a EC2. ID: $COMMAND_ID"
          echo "Esperando a que la instancia EC2 termine de desplegar Despachos..."

          # Obliga a GitHub a esperar el resultado final
          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ secrets.EC2_INSTANCE_ID }}
