name: CI/CD Backend Ventas (EKS)

on:
  push:
    branches: ["main"]

jobs:
  build-push-deploy-ventas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: us-east-1

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push a ECR
        run: |
          cd back-Ventas_SpringBoot/Springboot-API-REST
          docker build -t app-backend-ventas .
          docker tag app-backend-ventas:latest 174448597449.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
          docker push 174448597449.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest

      - name: Desplegar en Amazon EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_CLUSTER_NAME }}
          
          # 1. Asegurar que la base de datos y sus secretos existan
          kubectl apply -f k8s/mysql.yaml
          
          # 2. Eliminar el deployment anterior para forzar recreación limpia
          kubectl delete deployment backend-ventas --ignore-not-found
          
          # 3. Aplicar los nuevos manifiestos
          kubectl apply -f k8s/backend-ventas.yaml
