name: CI/CD Frontend (EKS)

on:
  push:
    branches: ["main"]

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: us-east-1

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push a ECR
        run: |
          cd front_despacho
          docker build -t app-frontend .
          docker tag app-frontend:latest 174448597449.dkr.ecr.us-east-1.amazonaws.com/front:latest
          docker push 174448597449.dkr.ecr.us-east-1.amazonaws.com/front:latest

      - name: Desplegar en Amazon EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_CLUSTER_NAME }}
          
          # 1. Eliminar el deployment anterior para forzar recreación limpia
          # Nota: Solo borramos el 'deployment', no el 'service', para que no cambie tu URL pública
          kubectl delete deployment frontend --ignore-not-found
          
          # 2. Aplicar los nuevos manifiestos
          kubectl apply -f k8s/frontend.yaml
